apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: docker.io/beomzh/chat-app:v1  
        ports:
        - containerPort: 3000

